# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
minecraft_version=26.2
official_mappings=true
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.4.0
maven_group=silversword
archives_base_name=ProjectAxiom

# Dependencies
fabric_api_version=0.152.1+26.2