# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
minecraft_version=26.3
official_mappings=true
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.4.0
maven_group=silversword
archives_base_name=ProjectAxiom

# Dependencies
fabric_api_version=0.161.0+26.3

# Java 25 toolchain - kiinnit‰ JDK, jotta Gradle ei poimi v‰‰ri‰ asennuksia
org.gradle.java.installations.paths=C:\\Program Files\\Microsoft\\jdk-25.0.4.101-hotspot,C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.4.1-hotspot
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false