package silversword.axiom.client.utils;

import com.mojang.blaze3d.platform.InputConstants;

import java.util.HashMap;
import java.util.Map;

public class KeyNames {
    private static final Map<Integer, String> KEY_NAMES = new HashMap<>();

    static {
        KEY_NAMES.put(InputConstants.KEY_SPACE, "Space");
        KEY_NAMES.put(InputConstants.KEY_APOSTROPHE, "'");
        KEY_NAMES.put(InputConstants.KEY_COMMA, ",");
        KEY_NAMES.put(InputConstants.KEY_MINUS, "-");
        KEY_NAMES.put(InputConstants.KEY_PERIOD, ".");
        KEY_NAMES.put(InputConstants.KEY_SLASH, "/");
        KEY_NAMES.put(InputConstants.KEY_0, "0");
        KEY_NAMES.put(InputConstants.KEY_1, "1");
        KEY_NAMES.put(InputConstants.KEY_2, "2");
        KEY_NAMES.put(InputConstants.KEY_3, "3");
        KEY_NAMES.put(InputConstants.KEY_4, "4");
        KEY_NAMES.put(InputConstants.KEY_5, "5");
        KEY_NAMES.put(InputConstants.KEY_6, "6");
        KEY_NAMES.put(InputConstants.KEY_7, "7");
        KEY_NAMES.put(InputConstants.KEY_8, "8");
        KEY_NAMES.put(InputConstants.KEY_9, "9");
        KEY_NAMES.put(InputConstants.KEY_SEMICOLON, ";");
        KEY_NAMES.put(InputConstants.KEY_EQUALS, "=");
        KEY_NAMES.put(InputConstants.KEY_A, "A");
        KEY_NAMES.put(InputConstants.KEY_B, "B");
        KEY_NAMES.put(InputConstants.KEY_C, "C");
        KEY_NAMES.put(InputConstants.KEY_D, "D");
        KEY_NAMES.put(InputConstants.KEY_E, "E");
        KEY_NAMES.put(InputConstants.KEY_F, "F");
        KEY_NAMES.put(InputConstants.KEY_G, "G");
        KEY_NAMES.put(InputConstants.KEY_H, "H");
        KEY_NAMES.put(InputConstants.KEY_I, "I");
        KEY_NAMES.put(InputConstants.KEY_J, "J");
        KEY_NAMES.put(InputConstants.KEY_K, "K");
        KEY_NAMES.put(InputConstants.KEY_L, "L");
        KEY_NAMES.put(InputConstants.KEY_M, "M");
        KEY_NAMES.put(InputConstants.KEY_N, "N");
        KEY_NAMES.put(InputConstants.KEY_O, "O");
        KEY_NAMES.put(InputConstants.KEY_P, "P");
        KEY_NAMES.put(InputConstants.KEY_Q, "Q");
        KEY_NAMES.put(InputConstants.KEY_R, "R");
        KEY_NAMES.put(InputConstants.KEY_S, "S");
        KEY_NAMES.put(InputConstants.KEY_T, "T");
        KEY_NAMES.put(InputConstants.KEY_U, "U");
        KEY_NAMES.put(InputConstants.KEY_V, "V");
        KEY_NAMES.put(InputConstants.KEY_W, "W");
        KEY_NAMES.put(InputConstants.KEY_X, "X");
        KEY_NAMES.put(InputConstants.KEY_Y, "Y");
        KEY_NAMES.put(InputConstants.KEY_Z, "Z");
        KEY_NAMES.put(InputConstants.KEY_LBRACKET, "[");
        KEY_NAMES.put(InputConstants.KEY_BACKSLASH, "\\");
        KEY_NAMES.put(InputConstants.KEY_RBRACKET, "]");
        KEY_NAMES.put(InputConstants.KEY_GRAVE, "`");
        KEY_NAMES.put(InputConstants.KEY_ESCAPE, "Escape");
        KEY_NAMES.put(InputConstants.KEY_RETURN, "Enter");
        KEY_NAMES.put(InputConstants.KEY_TAB, "Tab");
        KEY_NAMES.put(InputConstants.KEY_BACKSPACE, "Backspace");
        KEY_NAMES.put(InputConstants.KEY_INSERT, "Insert");
        KEY_NAMES.put(InputConstants.KEY_DELETE, "Delete");
        KEY_NAMES.put(InputConstants.KEY_RIGHT, "Right");
        KEY_NAMES.put(InputConstants.KEY_LEFT, "Left");
        KEY_NAMES.put(InputConstants.KEY_DOWN, "Down");
        KEY_NAMES.put(InputConstants.KEY_UP, "Up");
        KEY_NAMES.put(InputConstants.KEY_PAGEUP, "Page Up");
        KEY_NAMES.put(InputConstants.KEY_PAGEDOWN, "Page Down");
        KEY_NAMES.put(InputConstants.KEY_HOME, "Home");
        KEY_NAMES.put(InputConstants.KEY_END, "End");
        KEY_NAMES.put(InputConstants.KEY_CAPSLOCK, "Caps Lock");
        KEY_NAMES.put(InputConstants.KEY_SCROLLLOCK, "Scroll Lock");
        KEY_NAMES.put(InputConstants.KEY_NUMLOCK, "Num Lock");
        KEY_NAMES.put(InputConstants.KEY_PRINTSCREEN, "Print Screen");
        KEY_NAMES.put(InputConstants.KEY_PAUSE, "Pause");
        KEY_NAMES.put(InputConstants.KEY_F1, "F1");
        KEY_NAMES.put(InputConstants.KEY_F2, "F2");
        KEY_NAMES.put(InputConstants.KEY_F3, "F3");
        KEY_NAMES.put(InputConstants.KEY_F4, "F4");
        KEY_NAMES.put(InputConstants.KEY_F5, "F5");
        KEY_NAMES.put(InputConstants.KEY_F6, "F6");
        KEY_NAMES.put(InputConstants.KEY_F7, "F7");
        KEY_NAMES.put(InputConstants.KEY_F8, "F8");
        KEY_NAMES.put(InputConstants.KEY_F9, "F9");
        KEY_NAMES.put(InputConstants.KEY_F10, "F10");
        KEY_NAMES.put(InputConstants.KEY_F11, "F11");
        KEY_NAMES.put(InputConstants.KEY_F12, "F12");
        KEY_NAMES.put(InputConstants.KEY_F13, "F13");
        KEY_NAMES.put(InputConstants.KEY_F14, "F14");
        KEY_NAMES.put(InputConstants.KEY_F15, "F15");
        KEY_NAMES.put(InputConstants.KEY_F16, "F16");
        KEY_NAMES.put(InputConstants.KEY_F17, "F17");
        KEY_NAMES.put(InputConstants.KEY_F18, "F18");
        KEY_NAMES.put(InputConstants.KEY_F19, "F19");
        KEY_NAMES.put(InputConstants.KEY_F20, "F20");
        KEY_NAMES.put(InputConstants.KEY_F21, "F21");
        KEY_NAMES.put(InputConstants.KEY_F22, "F22");
        KEY_NAMES.put(InputConstants.KEY_F23, "F23");
        KEY_NAMES.put(InputConstants.KEY_F24, "F24");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD0, "Keypad 0");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD1, "Keypad 1");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD2, "Keypad 2");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD3, "Keypad 3");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD4, "Keypad 4");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD5, "Keypad 5");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD6, "Keypad 6");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD7, "Keypad 7");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD8, "Keypad 8");
        KEY_NAMES.put(InputConstants.KEY_NUMPAD9, "Keypad 9");
        KEY_NAMES.put(InputConstants.KEY_NUMPADCOMMA, "Keypad .");
        KEY_NAMES.put(InputConstants.KEY_ADD, "Keypad +");
        KEY_NAMES.put(InputConstants.KEY_MULTIPLY, "Keypad *");
        KEY_NAMES.put(InputConstants.KEY_NUMPADENTER, "Keypad Enter");
        KEY_NAMES.put(InputConstants.KEY_NUMPADEQUALS, "Keypad =");
        KEY_NAMES.put(InputConstants.KEY_LSHIFT, "Left Shift");
        KEY_NAMES.put(InputConstants.KEY_LCONTROL, "Left Control");
        KEY_NAMES.put(InputConstants.KEY_LALT, "Left Alt");
        KEY_NAMES.put(InputConstants.KEY_LGUI, "Left Super");
        KEY_NAMES.put(InputConstants.KEY_RSHIFT, "Right Shift");
        KEY_NAMES.put(InputConstants.KEY_RCONTROL, "Right Control");
        KEY_NAMES.put(InputConstants.KEY_RALT, "Right Alt");
        KEY_NAMES.put(InputConstants.KEY_RGUI, "Right Super");
    }

    public static String get(int keyCode) {
        return KEY_NAMES.getOrDefault(keyCode, "Key " + keyCode);
    }
}