package silversword.axiom.client.utils;

import org.lwjgl.glfw.GLFW;
import java.util.HashMap;
import java.util.Map;

public class KeyNames {
    private static final Map<Integer, String> KEY_NAMES = new HashMap<>();

    static {
        // Lisätään yleisimmät näppäimet
        KEY_NAMES.put(GLFW.GLFW_KEY_SPACE, "Space");
        KEY_NAMES.put(GLFW.GLFW_KEY_APOSTROPHE, "'");
        KEY_NAMES.put(GLFW.GLFW_KEY_COMMA, ",");
        KEY_NAMES.put(GLFW.GLFW_KEY_MINUS, "-");
        KEY_NAMES.put(GLFW.GLFW_KEY_PERIOD, ".");
        KEY_NAMES.put(GLFW.GLFW_KEY_SLASH, "/");
        KEY_NAMES.put(GLFW.GLFW_KEY_0, "0");
        KEY_NAMES.put(GLFW.GLFW_KEY_1, "1");
        KEY_NAMES.put(GLFW.GLFW_KEY_2, "2");
        KEY_NAMES.put(GLFW.GLFW_KEY_3, "3");
        KEY_NAMES.put(GLFW.GLFW_KEY_4, "4");
        KEY_NAMES.put(GLFW.GLFW_KEY_5, "5");
        KEY_NAMES.put(GLFW.GLFW_KEY_6, "6");
        KEY_NAMES.put(GLFW.GLFW_KEY_7, "7");
        KEY_NAMES.put(GLFW.GLFW_KEY_8, "8");
        KEY_NAMES.put(GLFW.GLFW_KEY_9, "9");
        KEY_NAMES.put(GLFW.GLFW_KEY_SEMICOLON, ";");
        KEY_NAMES.put(GLFW.GLFW_KEY_EQUAL, "=");
        KEY_NAMES.put(GLFW.GLFW_KEY_A, "A");
        KEY_NAMES.put(GLFW.GLFW_KEY_B, "B");
        KEY_NAMES.put(GLFW.GLFW_KEY_C, "C");
        KEY_NAMES.put(GLFW.GLFW_KEY_D, "D");
        KEY_NAMES.put(GLFW.GLFW_KEY_E, "E");
        KEY_NAMES.put(GLFW.GLFW_KEY_F, "F");
        KEY_NAMES.put(GLFW.GLFW_KEY_G, "G");
        KEY_NAMES.put(GLFW.GLFW_KEY_H, "H");
        KEY_NAMES.put(GLFW.GLFW_KEY_I, "I");
        KEY_NAMES.put(GLFW.GLFW_KEY_J, "J");
        KEY_NAMES.put(GLFW.GLFW_KEY_K, "K");
        KEY_NAMES.put(GLFW.GLFW_KEY_L, "L");
        KEY_NAMES.put(GLFW.GLFW_KEY_M, "M");
        KEY_NAMES.put(GLFW.GLFW_KEY_N, "N");
        KEY_NAMES.put(GLFW.GLFW_KEY_O, "O");
        KEY_NAMES.put(GLFW.GLFW_KEY_P, "P");
        KEY_NAMES.put(GLFW.GLFW_KEY_Q, "Q");
        KEY_NAMES.put(GLFW.GLFW_KEY_R, "R");
        KEY_NAMES.put(GLFW.GLFW_KEY_S, "S");
        KEY_NAMES.put(GLFW.GLFW_KEY_T, "T");
        KEY_NAMES.put(GLFW.GLFW_KEY_U, "U");
        KEY_NAMES.put(GLFW.GLFW_KEY_V, "V");
        KEY_NAMES.put(GLFW.GLFW_KEY_W, "W");
        KEY_NAMES.put(GLFW.GLFW_KEY_X, "X");
        KEY_NAMES.put(GLFW.GLFW_KEY_Y, "Y");
        KEY_NAMES.put(GLFW.GLFW_KEY_Z, "Z");
        KEY_NAMES.put(GLFW.GLFW_KEY_LEFT_BRACKET, "[");
        KEY_NAMES.put(GLFW.GLFW_KEY_BACKSLASH, "\\");
        KEY_NAMES.put(GLFW.GLFW_KEY_RIGHT_BRACKET, "]");
        KEY_NAMES.put(GLFW.GLFW_KEY_GRAVE_ACCENT, "`");
        KEY_NAMES.put(GLFW.GLFW_KEY_WORLD_1, "World 1");
        KEY_NAMES.put(GLFW.GLFW_KEY_WORLD_2, "World 2");
        KEY_NAMES.put(GLFW.GLFW_KEY_ESCAPE, "Escape");
        KEY_NAMES.put(GLFW.GLFW_KEY_ENTER, "Enter");
        KEY_NAMES.put(GLFW.GLFW_KEY_TAB, "Tab");
        KEY_NAMES.put(GLFW.GLFW_KEY_BACKSPACE, "Backspace");
        KEY_NAMES.put(GLFW.GLFW_KEY_INSERT, "Insert");
        KEY_NAMES.put(GLFW.GLFW_KEY_DELETE, "Delete");
        KEY_NAMES.put(GLFW.GLFW_KEY_RIGHT, "Right");
        KEY_NAMES.put(GLFW.GLFW_KEY_LEFT, "Left");
        KEY_NAMES.put(GLFW.GLFW_KEY_DOWN, "Down");
        KEY_NAMES.put(GLFW.GLFW_KEY_UP, "Up");
        KEY_NAMES.put(GLFW.GLFW_KEY_PAGE_UP, "Page Up");
        KEY_NAMES.put(GLFW.GLFW_KEY_PAGE_DOWN, "Page Down");
        KEY_NAMES.put(GLFW.GLFW_KEY_HOME, "Home");
        KEY_NAMES.put(GLFW.GLFW_KEY_END, "End");
        KEY_NAMES.put(GLFW.GLFW_KEY_CAPS_LOCK, "Caps Lock");
        KEY_NAMES.put(GLFW.GLFW_KEY_SCROLL_LOCK, "Scroll Lock");
        KEY_NAMES.put(GLFW.GLFW_KEY_NUM_LOCK, "Num Lock");
        KEY_NAMES.put(GLFW.GLFW_KEY_PRINT_SCREEN, "Print Screen");
        KEY_NAMES.put(GLFW.GLFW_KEY_PAUSE, "Pause");
        KEY_NAMES.put(GLFW.GLFW_KEY_F1, "F1");
        KEY_NAMES.put(GLFW.GLFW_KEY_F2, "F2");
        KEY_NAMES.put(GLFW.GLFW_KEY_F3, "F3");
        KEY_NAMES.put(GLFW.GLFW_KEY_F4, "F4");
        KEY_NAMES.put(GLFW.GLFW_KEY_F5, "F5");
        KEY_NAMES.put(GLFW.GLFW_KEY_F6, "F6");
        KEY_NAMES.put(GLFW.GLFW_KEY_F7, "F7");
        KEY_NAMES.put(GLFW.GLFW_KEY_F8, "F8");
        KEY_NAMES.put(GLFW.GLFW_KEY_F9, "F9");
        KEY_NAMES.put(GLFW.GLFW_KEY_F10, "F10");
        KEY_NAMES.put(GLFW.GLFW_KEY_F11, "F11");
        KEY_NAMES.put(GLFW.GLFW_KEY_F12, "F12");
        KEY_NAMES.put(GLFW.GLFW_KEY_F13, "F13");
        KEY_NAMES.put(GLFW.GLFW_KEY_F14, "F14");
        KEY_NAMES.put(GLFW.GLFW_KEY_F15, "F15");
        KEY_NAMES.put(GLFW.GLFW_KEY_F16, "F16");
        KEY_NAMES.put(GLFW.GLFW_KEY_F17, "F17");
        KEY_NAMES.put(GLFW.GLFW_KEY_F18, "F18");
        KEY_NAMES.put(GLFW.GLFW_KEY_F19, "F19");
        KEY_NAMES.put(GLFW.GLFW_KEY_F20, "F20");
        KEY_NAMES.put(GLFW.GLFW_KEY_F21, "F21");
        KEY_NAMES.put(GLFW.GLFW_KEY_F22, "F22");
        KEY_NAMES.put(GLFW.GLFW_KEY_F23, "F23");
        KEY_NAMES.put(GLFW.GLFW_KEY_F24, "F24");
        KEY_NAMES.put(GLFW.GLFW_KEY_F25, "F25");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_0, "Keypad 0");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_1, "Keypad 1");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_2, "Keypad 2");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_3, "Keypad 3");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_4, "Keypad 4");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_5, "Keypad 5");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_6, "Keypad 6");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_7, "Keypad 7");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_8, "Keypad 8");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_9, "Keypad 9");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_DECIMAL, "Keypad .");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_DIVIDE, "Keypad /");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_MULTIPLY, "Keypad *");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_SUBTRACT, "Keypad -");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_ADD, "Keypad +");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_ENTER, "Keypad Enter");
        KEY_NAMES.put(GLFW.GLFW_KEY_KP_EQUAL, "Keypad =");
        KEY_NAMES.put(GLFW.GLFW_KEY_LEFT_SHIFT, "Left Shift");
        KEY_NAMES.put(GLFW.GLFW_KEY_LEFT_CONTROL, "Left Control");
        KEY_NAMES.put(GLFW.GLFW_KEY_LEFT_ALT, "Left Alt");
        KEY_NAMES.put(GLFW.GLFW_KEY_LEFT_SUPER, "Left Super");
        KEY_NAMES.put(GLFW.GLFW_KEY_RIGHT_SHIFT, "Right Shift");
        KEY_NAMES.put(GLFW.GLFW_KEY_RIGHT_CONTROL, "Right Control");
        KEY_NAMES.put(GLFW.GLFW_KEY_RIGHT_ALT, "Right Alt");
        KEY_NAMES.put(GLFW.GLFW_KEY_RIGHT_SUPER, "Right Super");
        KEY_NAMES.put(GLFW.GLFW_KEY_MENU, "Menu");
    }

    public static String get(int keyCode) {
        return KEY_NAMES.getOrDefault(keyCode, "Key " + keyCode);
    }
}